spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine
    username: root
    password: testtest

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080
# example values

indexing-settings:
  sites:
#    - url: http://cimus.biz
#      name: Cimus
#    - url: https://nikoartgallery.com
#      name: Nikoartgallery

    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru