spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine
    username: root
    password: testtest

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8082

#server:
#  servlet:
#    context-path: /admin
conf:
  sitesUrl:
    - http://www.playback.ru
    - https://www.skillbox.ru
  sitesName:
    - Плейбек.ру
    - Skillbox
  userAgent: Mozilla/5.0 (Windows NT 6.1; rv:98.0) Gecko/20100101 Firefox/98.0
  referrer: http://google.com

#logging:
#  level:
#    org.springframework.web: trace
#    org.apache: trace